### ISSUE TITLE
Error while running demo

### ISSUE THREAD

**Issue by leonidcan** [pythononwheels/pow_devel#54]
Followed exact steps from quick start demo and getting this error (windows and ubuntu the same error)

Traceback (most recent call last):
  File "C:\Work\pow\todo\server.py", line 16, in <module>
    from todo.lib.application import Application, log_handler
  File "c:\Work\pow\todo\lib\application.py", line 12, in <module>
    from todo.database.sqldblib import Base, Session, engine
  File "c:\Work\pow\todo\database\sqldblib.py", line 42, in <module>
    metadata = MetaData(engine)
  File "C:\Work\pow\todo\lib\site-packages\sqlalchemy\sql\schema.py", line 5231, in __init__
    raise exc.ArgumentError(
sqlalchemy.exc.ArgumentError: expected schema argument to be a string, got <class 'sqlalchemy.engine.base.Engine'>.

**Comment by pythononwheels** [comment]
Hi, I will be checking this.

**Comment by pythononwheels** [comment]
This is due to some major changes in sqlalchemy 2.0.
As a quick fix: in your virtual environment:

`pip uninstall sqlalchemy `


`pip install sqlalchemy==1.4.46`

`pip freeze` 

should show you the correct version of sqlalchemy now.

I will adapt the binding in the package.
Thanks for the info !

**Comment by pythononwheels** [comment]
can you check if the sqlqlchemy version was causing the issue ?
